export const rawPermissions = {
  Calculation: {
    create: 'Calculation.create',
    index: 'Calculation.index',
    show: 'Calculation.show',
    update: 'Calculation.update',
    destroy: 'Calculation.destroy',
    manage: 'Calculation.manage',
  },
  User: {
    create: 'User.create',
    index: 'User.index',
    show: 'User.show',
    update: 'User.update',
    destroy: 'User.destroy',
    manage: 'User.manage',
    accept_eula: 'User.accept_eula',
  },
  Selection: {
    create: 'Selection.create',
    index: 'Selection.index',
    show: 'Selection.show',
    update: 'Selection.update',
    destroy: 'Selection.destroy',
    manage: 'Selection.manage',
  },
  Setting: {
    create: 'Setting.create',
    index: 'Setting.index',
    show: 'Setting.show',
    update: 'Setting.update',
    destroy: 'Setting.destroy',
    manage: 'Setting.manage',
    read_tubes: 'Setting.read_tubes',
  },
  FanModel: {
    create: 'FanModel.create',
    index: 'FanModel.index',
    show: 'FanModel.show',
    update: 'FanModel.update',
    destroy: 'FanModel.destroy',
    manage: 'FanModel.manage',
  },
  Polynomial: {
    create: 'Polynomial.create',
    index: 'Polynomial.index',
    show: 'Polynomial.show',
    update: 'Polynomial.update',
    destroy: 'Polynomial.destroy',
    manage: 'Polynomial.manage',
  },
  Development: {
    index: 'Development.index',
    show: 'Development.show',
  },
}
