export const drycoolerDesignData = [
  {
    id: 1,
    step: 'Input parameters',
    section: 'Performance',
    variable: 'capacity',
    unitMeasuresIds: [
      5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 163,
    ],
  },
  {
    id: 2,
    step: 'Input parameters',
    section: 'Liquid',
    variable: 'inlet_temperature',
    unitMeasuresIds: [32, 33, 34],
  },
  {
    id: 3,
    step: 'Input parameters',
    section: 'Liquid',
    variable: 'outlet_temperature',
    unitMeasuresIds: [32, 33, 34],
  },
  {
    id: 4,
    step: 'Input parameters',
    section: 'Liquid',
    variable: 'max_pressure_drop',
    unitMeasuresIds: [39, 41, 42, 44, 45, 46, 47, 48, 50, 51, 53],
  },
  {
    id: 5,
    step: 'Input parameters',
    section: 'Air',
    variable: 'inlet_temperature',
    unitMeasuresIds: [32, 33, 34],
  },
  {
    id: 6,
    step: 'Input parameters',
    section: 'Air',
    variable: 'min_operative_temperature',
    unitMeasuresIds: [32, 33, 34],
  },
  {
    id: 7,
    step: 'Input parameters',
    section: 'Air',
    variable: 'altitude',
    unitMeasuresIds: [1, 3],
  },
  {
    id: 8,
    step: 'Input parameters',
    section: 'Fans',
    variable: 'max_power_consumption',
    unitMeasuresIds: [5, 6],
  },
  {
    id: 9,
    step: 'Input parameters',
    section: 'Fans',
    variable: 'max_current_consumption',
    unitMeasuresIds: [165],
  },
  {
    id: 10,
    step: 'Input parameters',
    section: 'Fans',
    variable: 'esp',
    unitMeasuresIds: [40, 43, 44, 49, 50, 52, 53, 54],
  },
  {
    id: 11,
    step: 'Input parameters',
    section: 'Fans',
    variable: 'velocity',
    unitMeasuresIds: [168],
  },
  {
    id: 12,
    step: 'Input parameters',
    section: 'Fans',
    variable: 'diameter',
    unitMeasuresIds: [2],
  },
  {
    id: 13,
    step: 'Input parameters',
    section: 'Type and dimensions',
    variable: 'max_length',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 14,
    step: 'Input parameters',
    section: 'Type and dimensions',
    variable: 'max_height',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 15,
    step: 'Input parameters',
    section: 'Type and dimensions',
    variable: 'max_width',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 16,
    step: 'Input parameters',
    section: 'Noise',
    variable: 'max_sound_power',
    unitMeasuresIds: [167],
  },
  {
    id: 17,
    step: 'Input parameters',
    section: 'Noise',
    variable: 'max_sound_pressure',
    unitMeasuresIds: [167],
  },
  {
    id: 18,
    step: 'Input parameters',
    section: 'Noise',
    variable: 'distance',
    unitMeasuresIds: [1, 3],
  },
]
