export const drycoolerDetailData = [
  {
    id: 55,
    step: 'Model detail',
    section: 'Performance',
    variable: 'capacity',
    unitMeasuresIds: [
      5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 164,
    ],
  },
  {
    id: 56,
    step: 'Model detail',
    section: 'Liquid',
    variable: 'inlet_temperature',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 57,
    step: 'Model detail',
    section: 'Liquid',
    variable: 'outlet_temperature',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 58,
    step: 'Model detail',
    section: 'Liquid',
    variable: 'velocity',
    unitMeasuresIds: [56, 57],
  },
  {
    id: 59,
    step: 'Model detail',
    section: 'Liquid',
    variable: 'flow_rate',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 60,
    step: 'Model detail',
    section: 'Liquid',
    variable: 'tubes_pressure_drop',
    unitMeasuresIds: [40, 42, 43, 45, 46, 47, 48, 49, 51, 52, 54],
  },
  {
    id: 61,
    step: 'Model detail',
    section: 'Liquid',
    variable: 'headers_pressure_drop',
    unitMeasuresIds: [40, 42, 43, 45, 46, 47, 48, 49, 51, 52, 54],
  },
  {
    id: 62,
    step: 'Model detail',
    section: 'Liquid',
    variable: 'pressure_drop',
    unitMeasuresIds: [40, 42, 43, 45, 46, 47, 48, 49, 51, 52, 54],
  },
  {
    id: 63,
    step: 'Model detail',
    section: 'Liquid',
    variable: 'total_pressure_drop',
    unitMeasuresIds: [40, 42, 43, 45, 46, 47, 48, 49, 51, 52, 54],
  },
  {
    id: 64,
    step: 'Model detail',
    section: 'Air',
    variable: 'inlet_temperature',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 65,
    step: 'Model detail',
    section: 'Air',
    variable: 'outlet_temperature',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 66,
    step: 'Model detail',
    section: 'Air',
    variable: 'altitude',
    unitMeasuresIds: [1, 3],
  },
  {
    id: 67,
    step: 'Model detail',
    section: 'Air',
    variable: 'flow_rate',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 68,
    step: 'Model detail',
    section: 'Air',
    variable: 'velocity',
    unitMeasuresIds: [56, 57],
  },
  {
    id: 69,
    step: 'Model detail',
    section: 'Air',
    variable: 'pressure_drop',
    unitMeasuresIds: [41, 44, 45, 50, 51, 53, 54, 55],
  },
  {
    id: 70,
    step: 'Model detail',
    section: 'Fans',
    variable: 'velocity',
    unitMeasuresIds: [169],
  },
  {
    id: 71,
    step: 'Model detail',
    section: 'Fans',
    variable: 'nominal_rpm',
    unitMeasuresIds: [169],
  },
  {
    id: 72,
    step: 'Model detail',
    section: 'Fans',
    variable: 'esp',
    unitMeasuresIds: [41, 44, 45, 50, 51, 53, 54, 55],
  },
  {
    id: 73,
    step: 'Model detail',
    section: 'Fans',
    variable: 'diameter',
    unitMeasuresIds: [2],
  },
  {
    id: 74,
    step: 'Model detail',
    section: 'Fans',
    variable: 'operative_temperature',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 75,
    step: 'Model detail',
    section: 'Fans',
    variable: 'single_power',
    unitMeasuresIds: [5, 6],
  },
  {
    id: 76,
    step: 'Model detail',
    section: 'Fans',
    variable: 'nominal_single_power',
    unitMeasuresIds: [5, 6],
  },
  {
    id: 77,
    step: 'Model detail',
    section: 'Fans',
    variable: 'single_current',
    unitMeasuresIds: [166],
  },
  {
    id: 78,
    step: 'Model detail',
    section: 'Fans',
    variable: 'nominal_single_current',
    unitMeasuresIds: [166],
  },
  {
    id: 79,
    step: 'Model detail',
    section: 'Fans',
    variable: 'total_power',
    unitMeasuresIds: [5, 6],
  },
  {
    id: 80,
    step: 'Model detail',
    section: 'Fans',
    variable: 'nominal_total_power',
    unitMeasuresIds: [5, 6],
  },
  {
    id: 81,
    step: 'Model detail',
    section: 'Fans',
    variable: 'total_current',
    unitMeasuresIds: [166],
  },
  {
    id: 82,
    step: 'Model detail',
    section: 'Fans',
    variable: 'nominal_total_current',
    unitMeasuresIds: [166],
  },
  {
    id: 83,
    step: 'Model detail',
    section: 'Unit data',
    variable: 'length',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 84,
    step: 'Model detail',
    section: 'Unit data',
    variable: 'width',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 85,
    step: 'Model detail',
    section: 'Unit data',
    variable: 'height',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 86,
    step: 'Model detail',
    section: 'Unit data',
    variable: 'weight',
    unitMeasuresIds: [139, 167],
  },
  {
    id: 87,
    step: 'Model detail',
    section: 'Unit data',
    variable: 'inner_volume',
    unitMeasuresIds: [136, 137, 138, 147],
  },
  {
    id: 88,
    step: 'Model detail',
    section: 'Unit data',
    variable: 'exchange_area',
    unitMeasuresIds: [120, 143],
  },
  {
    id: 89,
    step: 'Model detail',
    section: 'Unit data',
    variable: 'inlet_connection_velocity',
    unitMeasuresIds: [56, 57],
  },
  {
    id: 90,
    step: 'Model detail',
    section: 'Unit data',
    variable: 'outlet_connection_velocity',
    unitMeasuresIds: [56, 57],
  },
  {
    id: 91,
    step: 'Model detail',
    section: 'Noise',
    variable: 'sound_power',
    unitMeasuresIds: [168],
  },
  {
    id: 92,
    step: 'Model detail',
    section: 'Noise',
    variable: 'sound_pressure',
    unitMeasuresIds: [168],
  },
  {
    id: 93,
    step: 'Model detail',
    section: 'Noise',
    variable: 'distance',
    unitMeasuresIds: [1, 3],
  },
  {
    id: 94,
    step: 'Model detail',
    section: 'Heat exchanger',
    variable: 'fin_spacing',
    unitMeasuresIds: [2, 4],
  },
  {
    id: 95,
    step: 'Model detail',
    section: 'Heat exchanger',
    variable: 'fin_pitch',
    unitMeasuresIds: [2, 4],
  },
  {
    id: 96,
    step: 'Model detail',
    section: 'Heat exchanger',
    variable: 'inner_volume',
    unitMeasuresIds: [136, 137, 138, 147],
  },
  {
    id: 97,
    step: 'Model detail',
    section: 'Heat exchanger',
    variable: 'exchange_area',
    unitMeasuresIds: [120, 143],
  },
  {
    id: 98,
    step: 'Model detail',
    section: 'Accessories',
    variable: 'price',
    unitMeasuresIds: [132],
  },
  {
    id: 99,
    step: 'Model detail',
    section: 'Accessories',
    variable: 'discounted_price',
    unitMeasuresIds: [132],
  },
  {
    id: 100,
    step: 'Model detail',
    section: 'Accessories',
    variable: 'total_price_accessories',
    unitMeasuresIds: [132],
  },
  {
    id: 101,
    step: 'Model detail',
    section: 'Accessories',
    variable: 'discounted_price_accessories',
    unitMeasuresIds: [132],
  },
  {
    id: 102,
    step: 'Model detail',
    section: 'Accessories',
    variable: 'total_price',
    unitMeasuresIds: [132],
  },
]
