export const drycoolerModelData = [
  {
    id: 19,
    step: 'Model choice',
    section: 'Entry conditions',
    variable: 'capacity',
    unitMeasuresIds: [
      5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 164,
    ],
  },
  {
    id: 20,
    step: 'Model choice',
    section: 'Entry conditions',
    variable: 'inlet_temperature',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 21,
    step: 'Model choice',
    section: 'Entry conditions',
    variable: 'outlet_temperature',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 22,
    step: 'Model choice',
    section: 'Entry conditions',
    variable: 'inlet_temperature',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 23,
    step: 'Model choice',
    section: 'Entry conditions',
    variable: 'esp',
    unitMeasuresIds: [41, 44, 45, 50, 51, 53, 54, 55],
  },
  {
    id: 24,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'power_exchange',
    unitMeasuresIds: [
      5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 164,
    ],
  },
  {
    id: 25,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'flow_rate',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 26,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'outlet_temperature',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 27,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'pressure_drop',
    unitMeasuresIds: [40, 42, 43, 45, 46, 47, 48, 49, 51, 52, 54],
  },
  {
    id: 28,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'air_flow_rate',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 29,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'sound_power',
    unitMeasuresIds: [168],
  },
  {
    id: 30,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'sound_pressure',
    unitMeasuresIds: [168],
  },
  {
    id: 31,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'velocity',
    unitMeasuresIds: [169],
  },
  {
    id: 32,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'current_consumption',
    unitMeasuresIds: [5, 6],
  },
  {
    id: 33,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'price',
    unitMeasuresIds: [132],
  },
  {
    id: 34,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'power_exchange',
    unitMeasuresIds: [
      5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 164,
    ],
  },
  {
    id: 35,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'outlet_temperature',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 36,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'flow_rate',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 37,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'pressure_drop',
    unitMeasuresIds: [40, 42, 43, 45, 46, 47, 48, 49, 51, 52, 54],
  },
  {
    id: 38,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'air_flow_rate',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 39,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'outlet_temperature',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 40,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'single_power',
    unitMeasuresIds: [5, 6],
  },
  {
    id: 41,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'nominal_single_power',
    unitMeasuresIds: [5, 6],
  },
  {
    id: 42,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'single_current',
    unitMeasuresIds: [166],
  },
  {
    id: 43,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'nominal_single_current',
    unitMeasuresIds: [166],
  },
  {
    id: 44,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'velocity',
    unitMeasuresIds: [169],
  },
  {
    id: 45,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'velocity_nominal',
    unitMeasuresIds: [169],
  },
  {
    id: 46,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'length',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 47,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'width',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 48,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'height',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 49,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'weight',
    unitMeasuresIds: [139, 167],
  },
  {
    id: 50,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'internal_volume',
    unitMeasuresIds: [136, 137, 138, 147],
  },
  {
    id: 51,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'exchange_area',
    unitMeasuresIds: [120, 143],
  },
  {
    id: 52,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'sound_pressure',
    unitMeasuresIds: [168],
  },
  {
    id: 53,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'sound_power',
    unitMeasuresIds: [168],
  },
  {
    id: 54,
    step: 'Model choice',
    section: 'Selected model detail table',
    variable: 'price',
    unitMeasuresIds: [132],
  },
]
