export const condenserDesignData = [
  {
    id: 1,
    step: 'Input parameters',
    section: 'Performance',
    variable: 'capacity',
    unitMeasuresIds: [
      5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 164,
    ],
  },
  {
    id: 2,
    step: 'Input parameters',
    section: 'Air',
    variable: 'drybulb',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 3,
    step: 'Input parameters',
    section: 'Air',
    variable: 'atmospheric_pressure',
    unitMeasuresIds: [],
  },
  {
    id: 4,
    step: 'Input parameters',
    section: 'Air',
    variable: 'altitude',
    unitMeasuresIds: [1, 3],
  },
  {
    id: 5,
    step: 'Input parameters',
    section: 'Fluid',
    variable: 'compressor',
    // Desuperheating: °F + Kelvin (delta)
    unitMeasuresIds: [33, 35],
  },
  {
    id: 6,
    step: 'Input parameters',
    section: 'Fluid',
    variable: 'inletTemperature',
    // Inlet Temp: °C + °F only
    unitMeasuresIds: [32, 33],
  },
  {
    id: 7,
    step: 'Input parameters',
    section: 'Fluid',
    variable: 'condensing',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 8,
    step: 'Input parameters',
    section: 'Fluid',
    variable: 'subCooling',
    // Subcooling delta: °F + Kelvin
    unitMeasuresIds: [33, 35],
  },
  {
    id: 9,
    step: 'Input parameters',
    section: 'Fluid',
    variable: 'outletTemperature',
    // Desired outlet Temp: °C + °F only
    unitMeasuresIds: [32, 33],
  },
  {
    id: 10,
    step: 'Input parameters',
    section: 'Dimensions',
    variable: 'maxLength',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 11,
    step: 'Input parameters',
    section: 'Dimensions',
    variable: 'maxHeight',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 12,
    step: 'Input parameters',
    section: 'Dimensions',
    variable: 'maxWidth',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 13,
    step: 'Input parameters',
    section: 'Fans',
    variable: 'esp',
    unitMeasuresIds: [41, 44, 45, 50, 51, 53, 54, 55],
  },
  {
    id: 14,
    step: 'Input parameters',
    section: 'Noise',
    variable: 'distance',
    unitMeasuresIds: [1, 3],
  },
  {
    id: 15,
    step: 'Input parameters',
    section: 'Air',
    variable: 'minOperativeTemperature',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 16,
    step: 'Input parameters',
    section: 'Noise',
    variable: 'maxSoundPower',
    unitMeasuresIds: [168],
  },
  {
    id: 17,
    step: 'Input parameters',
    section: 'Noise',
    variable: 'maxSoundPressure',
    unitMeasuresIds: [168],
  },
  {
    id: 18,
    step: 'Input parameters',
    section: 'Noise',
    variable: 'noiseTolerance',
    unitMeasuresIds: [168],
  },
]
