export const condenserDetailData = [
  {
    id: 20,
    step: 'Model detail',
    section: 'Adjustment Modules (capacity)',
    variable: 'calculated_capacity',
    unitMeasuresIds: [
      5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 163,
    ],
  },
  {
    id: 21,
    step: 'Model detail',
    section: 'Adjustment Modules (capacity)',
    variable: 'adjusted_capacity',
    unitMeasuresIds: [
      5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 163,
    ],
  },
  {
    id: 22,
    step: 'Model detail',
    section: 'Adjustment Modules (fan flows)',
    variable: 'min_fan_flow_rate',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 23,
    step: 'Model detail',
    section: 'Adjustment Modules (fan flows)',
    variable: 'max_fan_flow_rate',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 24,
    step: 'Model detail',
    section: 'Adjustment Modules (fan flows)',
    variable: 'adjusted_min_fans_flow',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 25,
    step: 'Model detail',
    section: 'Adjustment Modules (fan flows)',
    variable: 'adjusted_max_fans_flow',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 26,
    step: 'Model detail',
    section: 'Adjustment Modules (fan flows)',
    variable: 'calculated_fans_flow',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 27,
    step: 'Model detail',
    section: 'Adjustment Modules (fan flows)',
    variable: 'adjusted_fans_flow',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 28,
    step: 'Model detail',
    section: 'Performance',
    variable: 'real_capacity',
    unitMeasuresIds: [
      5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 163,
    ],
  },
  {
    id: 29,
    step: 'Model detail',
    section: 'Performance',
    variable: 'req_capacity',
    unitMeasuresIds: [
      5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 163,
    ],
  },
  {
    id: 30,
    step: 'Model detail',
    section: 'Performance',
    variable: 'inlet_air_temp',
    unitMeasuresIds: [32, 33, 34],
  },
  {
    id: 31,
    step: 'Model detail',
    section: 'Performance',
    variable: 'altitude',
    unitMeasuresIds: [1, 3],
  },
  {
    id: 32,
    step: 'Model detail',
    section: 'Performance',
    variable: 'air_flow',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 33,
    step: 'Model detail',
    section: 'Performance',
    variable: 'spl_in_acc',
    unitMeasuresIds: [167],
  },
  {
    id: 34,
    step: 'Model detail',
    section: 'Performance',
    variable: 'acc_power_level',
    unitMeasuresIds: [167],
  },
  {
    id: 35,
    step: 'Model detail',
    section: 'Performance',
    variable: 'at_requested_condensing_temp',
    unitMeasuresIds: [32, 33, 34],
  },
  {
    id: 36,
    step: 'Model detail',
    section: 'Performance',
    variable: 'at_real_condensing_temp',
    unitMeasuresIds: [32, 33, 34],
  },
  {
    id: 37,
    step: 'Model detail',
    section: 'Performance',
    variable: 'desuper_heat_temp',
    unitMeasuresIds: [32, 33, 34],
  },
  {
    id: 38,
    step: 'Model detail',
    section: 'Performance',
    variable: 'subCooling_temp',
    unitMeasuresIds: [32, 33, 34],
  },
  {
    id: 39,
    step: 'Model detail',
    section: 'Performance',
    variable: 'outlet_air_temp',
    unitMeasuresIds: [32, 33, 34],
  },
  {
    id: 40,
    step: 'Model detail',
    section: 'Performance',
    variable: 'ref_side_press_drop',
    unitMeasuresIds: [39, 41, 42, 44, 45, 46, 47, 48, 50, 51, 53],
  },
  {
    id: 41,
    step: 'Model detail',
    section: 'Performance',
    variable: 'air_side_press_drop',
    unitMeasuresIds: [40, 43, 44, 49, 50, 52, 53, 54],
  },
  {
    id: 42,
    step: 'Model detail',
    section: 'Performance',
    variable: 'at_distance',
    unitMeasuresIds: [1, 3],
  },
  {
    id: 43,
    step: 'Model detail',
    section: 'Performance',
    variable: 'surface',
    unitMeasuresIds: [119, 142],
  },
  {
    id: 44,
    step: 'Model detail',
    section: 'Performance',
    variable: 'weight',
    unitMeasuresIds: [138, 166],
  },
  {
    id: 45,
    step: 'Model detail',
    section: 'Performance',
    variable: 'internal_vol',
    unitMeasuresIds: [135, 136, 137, 146],
  },

  {
    id: 46,
    step: 'Model detail',
    section: 'Performance',
    variable: 'inlet_connection',
    unitMeasuresIds: [2, 4],
  },
  {
    id: 47,
    step: 'Model detail',
    section: 'Performance',
    variable: 'outlet_connection',
    unitMeasuresIds: [2, 4],
  },
  {
    id: 48,
    step: 'Model detail',
    section: 'Performance',
    variable: 'position_connection',
    unitMeasuresIds: [2, 4],
  },
  {
    id: 49,
    step: 'Model detail',
    section: 'Fans',
    variable: 'rpm',
    unitMeasuresIds: [168],
  },
  {
    id: 50,
    step: 'Model detail',
    section: 'Fans',
    variable: 'power_wp',
    unitMeasuresIds: [5, 6],
  },
  {
    id: 51,
    step: 'Model detail',
    section: 'Fans',
    variable: 'current_max',
    unitMeasuresIds: [165],
  },
  {
    id: 52,
    step: 'Model detail',
    section: 'Fans',
    variable: 'spl',
    unitMeasuresIds: [167],
  },
  {
    id: 53,
    step: 'Model detail',
    section: 'Fans',
    variable: 'power_level',
    unitMeasuresIds: [167],
  },
  {
    id: 54,
    step: 'Model detail',
    section: 'Fans',
    variable: 'voltage',
    unitMeasuresIds: [169],
  },
  {
    id: 55,
    step: 'Model detail',
    section: 'Fans',
    variable: 'frequency',
    unitMeasuresIds: [170],
  },
  {
    id: 56,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'lv1',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 57,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'lv2',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 58,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'lv3',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 59,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'lv4',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 60,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'lv5',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 61,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'wv1',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 62,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'wv2',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 63,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'hv1',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 64,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'hv2',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 65,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'hv3',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 66,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'hv4',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 67,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'p1',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 68,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'dv1',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 69,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'lh1',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 70,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'lh2',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 71,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'lh3',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 72,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'lh4',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 73,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'lh5',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 74,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'wh1',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 75,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'wh2',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 76,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'wh3',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 77,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'wh4',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 78,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'hh1',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 79,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'hh2',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 80,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'hh3',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 81,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'hh4',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 82,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'p2',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 83,
    step: 'Model detail',
    section: 'Geometric Parameters',
    variable: 'dh1',
    unitMeasuresIds: [1, 2, 3, 4],
  },
  {
    id: 84,
    step: 'Model detail',
    section: 'accessories',
    variable: 'accessoriesPrice',
    unitMeasuresIds: [131],
  },
  {
    id: 85,
    step: 'Model detail',
    section: 'accessories',
    variable: 'unitPrice',
    unitMeasuresIds: [131],
  },
  {
    id: 86,
    step: 'Model detail',
    section: 'accessories',
    variable: 'totalNetPrice',
    unitMeasuresIds: [131],
  },
]
