export const condenserEanalysisData = [
  {
    id: 97,
    step: 'Model detail',
    section: 'energy_analysis_calc_capacity',
    variable: 'starting_air_temp',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 98,
    step: 'Model detail',
    section: 'energy_analysis_calc_capacity',
    variable: 'final_air_temp',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 99,
    step: 'Model detail',
    section: 'energy_analysis_calc_capacity',
    variable: 'step',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 100,
    step: 'Model detail',
    section: 'energy_analysis_calc_capacity',
    variable: 'distance',
    unitMeasuresIds: [1, 3],
  },
  {
    id: 101,
    step: 'Model detail',
    section: 'energy_analysis_calc_capacity',
    variable: 'condensing_temp',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 102,
    step: 'Model detail',
    section: 'energy_analysis_calc_air',
    variable: 'fixed_capacity',
    unitMeasuresIds: [
      5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 164,
    ],
  },
  {
    id: 103,
    step: 'Model detail',
    section: 'energy_analysis_calc_air',
    variable: 'starting_air_temp',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 104,
    step: 'Model detail',
    section: 'energy_analysis_calc_air',
    variable: 'final_air_temp',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 105,
    step: 'Model detail',
    section: 'energy_analysis_calc_air',
    variable: 'step',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 106,
    step: 'Model detail',
    section: 'energy_analysis_calc_air',
    variable: 'distance',
    unitMeasuresIds: [1, 3],
  },
  {
    id: 107,
    step: 'Model detail',
    section: 'energy_analysis_calc_air',
    variable: 'condensing_temp',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 108,
    step: 'Model detail',
    section: 'energy_analysis_calc_single',
    variable: 'fixed_capacity',
    unitMeasuresIds: [
      5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 164,
    ],
  },
  {
    id: 109,
    step: 'Model detail',
    section: 'energy_analysis_calc_single',
    variable: 'intel_air_temp',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 110,
    step: 'Model detail',
    section: 'energy_analysis_calc_single',
    variable: 'distance',
    unitMeasuresIds: [1, 3],
  },
  {
    id: 111,
    step: 'Model detail',
    section: 'energy_analysis_calc_single',
    variable: 'condensing_temp',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 112,
    step: 'Model detail',
    section: 'energy_analysis_table',
    variable: 'air_temp_inlet',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 113,
    step: 'Model detail',
    section: 'energy_analysis_table',
    variable: 'capacity',
    unitMeasuresIds: [
      5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 164,
    ],
  },
  {
    id: 114,
    step: 'Model detail',
    section: 'energy_analysis_table',
    variable: 'air_flow',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 115,
    step: 'Model detail',
    section: 'energy_analysis_table',
    variable: 'dp_air',
    unitMeasuresIds: [41, 44, 45, 50, 51, 53, 54, 55],
  },
  {
    id: 116,
    step: 'Model detail',
    section: 'energy_analysis_table',
    variable: 'spl',
    unitMeasuresIds: [168],
  },
  {
    id: 117,
    step: 'Model detail',
    section: 'energy_analysis_table',
    variable: 'rpm',
    unitMeasuresIds: [169],
  },
  {
    id: 118,
    step: 'Model detail',
    section: 'energy_analysis_table',
    variable: 'power',
    unitMeasuresIds: [5, 6],
  },
  {
    id: 119,
    step: 'Model detail',
    section: 'energy_analysis_table',
    variable: 'current_all_fans',
    unitMeasuresIds: [166],
  },
  {
    id: 120,
    step: 'Model detail',
    section: 'energy_analysis_table',
    variable: 'tube_vol',
    unitMeasuresIds: [136, 137, 138, 147],
  },
  {
    id: 121,
    step: 'Model detail',
    section: 'energy_analysis_table',
    variable: 'weight',
    unitMeasuresIds: [139, 167],
  },
  {
    id: 122,
    step: 'Model detail',
    section: 'energy_analysis_table',
    variable: 'connections_outlet',
    unitMeasuresIds: [2, 4],
  },
  {
    id: 123,
    step: 'Model detail',
    section: 'energy_analysis_table',
    variable: 'connections_inlet',
    unitMeasuresIds: [2, 4],
  },
  {
    id: 124,
    step: 'Model detail',
    section: 'energy_analysis_table',
    variable: 'price',
    unitMeasuresIds: [132],
  },
]
