export const condenserModelData = [
  {
    id: 9,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'capacity',
    unitMeasuresIds: [
      5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 163,
    ],
  },
  {
    id: 10,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'airflow',
    unitMeasuresIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 11,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'spl',
    unitMeasuresIds: [167],
  },
  {
    id: 12,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'fan_motors_no',
    unitMeasuresIds: [],
  },
  {
    id: 13,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'fan_motors_rpm',
    unitMeasuresIds: [168],
  },
  {
    id: 14,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'fan_motors_power',
    unitMeasuresIds: [5, 6],
  },
  {
    id: 14,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'fan_motors_current',
    unitMeasuresIds: [165],
  },
  {
    id: 15,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'tube_volume',
    unitMeasuresIds: [135, 136, 137, 146],
  },
  {
    id: 16,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'weight',
    unitMeasuresIds: [138, 166],
  },
  {
    id: 17,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'connection_outlet',
    unitMeasuresIds: [2, 4],
  },
  {
    id: 18,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'connection_inlet',
    unitMeasuresIds: [2, 4],
  },
  {
    id: 19,
    step: 'Model choice',
    section: 'Model list table',
    variable: 'price',
    unitMeasuresIds: [131],
  },
]
