export const condenserWorkingData = [
  {
    id: 90,
    step: 'Working point',
    section: 'Working Point (air)',
    variable: 'airInletTemp',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 91,
    step: 'Working point',
    section: 'Working Point (air)',
    variable: 'wetBulb',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 137,
    step: 'Working point',
    section: 'Working Point (air)',
    variable: 'finalAirInletTemp',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 138,
    step: 'Working point',
    section: 'Working Point (air)',
    variable: 'tempStep',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 92,
    step: 'Working point',
    section: 'Working Point (liquid)',
    variable: 'liquidInletTemp',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 93,
    step: 'Working point',
    section: 'Working Point (liquid)',
    variable: 'liquidOutletTemp',
    unitMeasuresIds: [32, 33, 34, 35],
  },
  {
    id: 94,
    step: 'Working point',
    section: 'Working Point (liquid)',
    variable: 'liquidFlowRate',
    unitMeasuresIds: [152, 153, 154, 155, 156, 157, 142, 158, 159, 160, 161],
  },
  {
    id: 95,
    step: 'Working point',
    section: 'Working Point (ventilation)',
    variable: 'espTemp',
    unitMeasuresIds: [
      39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 130,
      146,
    ],
  },
  {
    id: 96,
    step: 'Working point',
    section: 'Working Point (ventilation)',
    variable: 'liquidDistanceTemp',
    unitMeasuresIds: [1, 2, 3, 4, 127, 128],
  },
]
