export default {
  VITE_AWS_LOGGER_LEVEL: 'VERBOSE',
  VITE_ENABLE_DEVELOPMENT_FEATURES: 'true',
  VITE_ENABLE_FORMIK_STATE_INSPECTOR: 'false',

  VITE_CUSTOMER_REGISTRATION_DISABLE_TABS_LOCKING: 'true',
  VITE_INTERNAL_REGISTRATION_DISABLE_TABS_LOCKING: 'true',
  VITE_COLLABORATOR_REGISTRATION_DISABLE_TABS_LOCKING: 'true',
}
