export type UnitType =
  | 'Measure'
  | 'Capacity'
  | 'Rate'
  | 'Temperature'
  | 'Fouling'
  | 'Pressure'
  | 'Velocity'
  | 'Density'
  | 'Specific Heat'
  | 'Dynamic viscosity'
  | 'Thermal conductivity'
  | 'Latent Heat'
  | 'Surface'
  | 'Volume'
  | 'Heat transfer coefficient'
  | 'Hentalpy'
  | 'Currency'
  | 'Weight'
  | 'Specific flow'
  | 'Specific humidity'
  | 'Rate Water'
  | 'Rate Water 24h'
  | 'Current'
  | 'Sound'
  | 'Rotation speed'
  | 'Voltage'
  | 'Frequency'

export type UnitDef = {
  id: number
  name: string
  type: UnitType
  factor: number
  delta: number
  decimalPlaces: number
}

export const UNITS: readonly UnitDef[] = [
  {
    id: 1,
    name: 'm',
    type: 'Measure',
    factor: 1000,
    delta: 0,
    decimalPlaces: 3,
  },
  { id: 2, name: 'mm', type: 'Measure', factor: 1, delta: 0, decimalPlaces: 0 },
  {
    id: 3,
    name: 'ft',
    type: 'Measure',
    factor: 304.8,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 4,
    name: '"',
    type: 'Measure',
    factor: 25.4,
    delta: 0,
    decimalPlaces: 1,
  },
  { id: 5, name: 'W', type: 'Capacity', factor: 1, delta: 0, decimalPlaces: 0 },
  {
    id: 6,
    name: 'kW',
    type: 'Capacity',
    factor: 1000,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 7,
    name: 'kcal/h',
    type: 'Capacity',
    factor: 1.163,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 8,
    name: 'Btu/h',
    type: 'Capacity',
    factor: 0.2930711,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 9,
    name: 'CV',
    type: 'Capacity',
    factor: 735.4988,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 10,
    name: 'HP',
    type: 'Capacity',
    factor: 745.6999,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 11,
    name: 'frig/h',
    type: 'Capacity',
    factor: 1.163,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 12,
    name: 'kcal/min',
    type: 'Capacity',
    factor: 69.78,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 13,
    name: 'erg/s',
    type: 'Capacity',
    factor: 0.0000001,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 14,
    name: 'Btu/s',
    type: 'Capacity',
    factor: 1055.06,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 15,
    name: 'Btu/min',
    type: 'Capacity',
    factor: 17.5843,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 16,
    name: 'kcal/s',
    type: 'Capacity',
    factor: 4186.8,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 17,
    name: 'kgf m/s',
    type: 'Capacity',
    factor: 9.80665,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 18,
    name: 'lbf ft/h',
    type: 'Capacity',
    factor: 0.000376616,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 19,
    name: 'lbf ft/min',
    type: 'Capacity',
    factor: 0.022597,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 20,
    name: 'lbf ft/s',
    type: 'Capacity',
    factor: 1.35582,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 21,
    name: 'ton(ref.)',
    type: 'Capacity',
    factor: 3516.85,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 22,
    name: 'm³/s',
    type: 'Rate',
    factor: 3600,
    delta: 0,
    decimalPlaces: 3,
  },
  { id: 23, name: 'm³/h', type: 'Rate', factor: 1, delta: 0, decimalPlaces: 1 },
  {
    id: 24,
    name: 'l/s',
    type: 'Rate',
    factor: 3.6,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 25,
    name: 'cft/s',
    type: 'Rate',
    factor: 101.94,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 26,
    name: 'cft/min (CFM)',
    type: 'Rate',
    factor: 1.699,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 27,
    name: 'Gal/min (GPM)',
    type: 'Rate',
    factor: 0.2271,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 28,
    name: 'kg/s',
    type: 'Rate',
    factor: 3600,
    delta: 0,
    decimalPlaces: 4,
  },
  { id: 29, name: 'kg/h', type: 'Rate', factor: 1, delta: 0, decimalPlaces: 1 },
  {
    id: 30,
    name: 'lb/s',
    type: 'Rate',
    factor: 1632.932532,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 31,
    name: 'lb/h',
    type: 'Rate',
    factor: 0.45359244,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 32,
    name: '°C',
    type: 'Temperature',
    factor: 1,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 33,
    name: '°F',
    type: 'Temperature',
    factor: 0.555555555556,
    delta: 32,
    decimalPlaces: 1,
  },
  {
    id: 34,
    name: 'K',
    type: 'Temperature',
    factor: 1,
    delta: 273,
    decimalPlaces: 2,
  },
  {
    id: 35,
    name: '(m² K)/W',
    type: 'Fouling',
    factor: 1,
    delta: 0,
    decimalPlaces: 6,
  },
  {
    id: 36,
    name: '(m² h °C)/kcal',
    type: 'Fouling',
    factor: 0.8598,
    delta: 0,
    decimalPlaces: 5,
  },
  {
    id: 37,
    name: '(ftq h °F)/Btu',
    type: 'Fouling',
    factor: 0.1761,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 38,
    name: 'atm',
    type: 'Pressure',
    factor: 1.01325,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 39,
    name: 'bar',
    type: 'Pressure',
    factor: 1,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 40,
    name: 'Pa',
    type: 'Pressure',
    factor: 0.00001,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 41,
    name: 'kPa',
    type: 'Pressure',
    factor: 0.01,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 42,
    name: 'mH2O',
    type: 'Pressure',
    factor: 0.0980665,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 43,
    name: 'mmH2O',
    type: 'Pressure',
    factor: 0.000098066,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 44,
    name: 'mmHg',
    type: 'Pressure',
    factor: 0.001333224,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 45,
    name: 'inHg',
    type: 'Pressure',
    factor: 0.03386389,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 46,
    name: 'psi',
    type: 'Pressure',
    factor: 0.06894757,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 47,
    name: 'at',
    type: 'Pressure',
    factor: 0.980665,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 48,
    name: 'Torr',
    type: 'Pressure',
    factor: 0.001333224,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 49,
    name: 'Ba',
    type: 'Pressure',
    factor: 0.000001,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 50,
    name: 'inH2O',
    type: 'Pressure',
    factor: 0.002490889,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 51,
    name: 'kgf/cm²',
    type: 'Pressure',
    factor: 0.980665,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 52,
    name: 'kgf/m²',
    type: 'Pressure',
    factor: 0.000098066,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 53,
    name: 'lbf/ft²',
    type: 'Pressure',
    factor: 0.000478802,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 54,
    name: 'pdl/ft²',
    type: 'Pressure',
    factor: 0.000014881,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 55,
    name: 'm/s',
    type: 'Velocity',
    factor: 1,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 56,
    name: 'ft/s',
    type: 'Velocity',
    factor: 0.3048,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 57,
    name: 'ft/h',
    type: 'Velocity',
    factor: 0.00008466667,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 58,
    name: 'ft/min',
    type: 'Velocity',
    factor: 0.00508,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 59,
    name: 'in/s',
    type: 'Velocity',
    factor: 0.0254,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 60,
    name: 'km/h',
    type: 'Velocity',
    factor: 0.2777778,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 61,
    name: 'kn',
    type: 'Velocity',
    factor: 0.5144444,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 62,
    name: 'm/h',
    type: 'Velocity',
    factor: 0.0002777778,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 63,
    name: 'mi/h',
    type: 'Velocity',
    factor: 0.44704,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 64,
    name: 'mi/min',
    type: 'Velocity',
    factor: 26.8224,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 65,
    name: 'mi/s',
    type: 'Velocity',
    factor: 1609.344,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 66,
    name: 'kg/m³',
    type: 'Density',
    factor: 1,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 67,
    name: 'g/cm³',
    type: 'Density',
    factor: 1000,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 68,
    name: 'gr/gal(US)',
    type: 'Density',
    factor: 0.01711806,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 69,
    name: 'kg/L',
    type: 'Density',
    factor: 1000,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 70,
    name: 'lb/ft³',
    type: 'Density',
    factor: 16.01846,
    delta: 0,
    decimalPlaces: 6,
  },
  {
    id: 71,
    name: 'lb/gal(Im)',
    type: 'Density',
    factor: 99.77637,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 72,
    name: 'lb/gal(US)',
    type: 'Density',
    factor: 119.8264,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 73,
    name: 'lb/in³',
    type: 'Density',
    factor: 27679.91,
    delta: 0,
    decimalPlaces: 5,
  },
  {
    id: 74,
    name: 'lb/yd³',
    type: 'Density',
    factor: 0.5932764,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 75,
    name: 'oz/gal(Im)',
    type: 'Density',
    factor: 6.236023,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 76,
    name: 'oz/gal(US)',
    type: 'Density',
    factor: 7.489152,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 77,
    name: 'oz/in³',
    type: 'Density',
    factor: 1729.994,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 78,
    name: 'slug/ft³',
    type: 'Density',
    factor: 515.3788,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 79,
    name: 't/m³',
    type: 'Density',
    factor: 1000,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 80,
    name: '(long) ton/yd³',
    type: 'Density',
    factor: 1328.939,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 81,
    name: '(short) ton/yd³',
    type: 'Density',
    factor: 1186.553,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 82,
    name: 'g/L',
    type: 'Density',
    factor: 1,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 83,
    name: 'J/(kg K)',
    type: 'Specific Heat',
    factor: 1,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 84,
    name: 'm²/(s² K)',
    type: 'Specific Heat',
    factor: 1,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 85,
    name: 'Btu/(lb °R)',
    type: 'Specific Heat',
    factor: 4186.8,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 86,
    name: 'Btu/(slug °R)',
    type: 'Specific Heat',
    factor: 130.1298,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 87,
    name: 'cal/(g K)',
    type: 'Specific Heat',
    factor: 4186.8,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 88,
    name: 'kcal/(kg K)',
    type: 'Specific Heat',
    factor: 4186.8,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 89,
    name: 'kg/(m s)',
    type: 'Dynamic viscosity',
    factor: 1,
    delta: 0,
    decimalPlaces: 8,
  },
  {
    id: 90,
    name: 'Pa s',
    type: 'Dynamic viscosity',
    factor: 1,
    delta: 0,
    decimalPlaces: 8,
  },
  {
    id: 91,
    name: 'cP',
    type: 'Dynamic viscosity',
    factor: 0.001,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 92,
    name: 'kgf h/m²',
    type: 'Dynamic viscosity',
    factor: 35303.94,
    delta: 0,
    decimalPlaces: 6,
  },
  {
    id: 93,
    name: 'kgf s/m²',
    type: 'Dynamic viscosity',
    factor: 9.80665,
    delta: 0,
    decimalPlaces: 8,
  },
  {
    id: 94,
    name: 'kg/(m h)',
    type: 'Dynamic viscosity',
    factor: 0.0002777778,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 95,
    name: 'lbf h/ft²',
    type: 'Dynamic viscosity',
    factor: 172368.9,
    delta: 0,
    decimalPlaces: 5,
  },
  {
    id: 96,
    name: 'lbf s/ft²',
    type: 'Dynamic viscosity',
    factor: 47.88026,
    delta: 0,
    decimalPlaces: 6,
  },
  {
    id: 97,
    name: 'lbf s/in²',
    type: 'Dynamic viscosity',
    factor: 6894.757,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 98,
    name: 'lb/(ft h)',
    type: 'Dynamic viscosity',
    factor: 0.0004133789,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 99,
    name: 'lb/(ft s)',
    type: 'Dynamic viscosity',
    factor: 1.488164,
    delta: 0,
    decimalPlaces: 8,
  },
  {
    id: 100,
    name: 'N s/m²',
    type: 'Dynamic viscosity',
    factor: 1,
    delta: 0,
    decimalPlaces: 8,
  },
  {
    id: 101,
    name: 'P',
    type: 'Dynamic viscosity',
    factor: 0.1,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 102,
    name: 'pdl s/ft²',
    type: 'Dynamic viscosity',
    factor: 1.488164,
    delta: 0,
    decimalPlaces: 8,
  },
  {
    id: 103,
    name: 'slug/(ft s)',
    type: 'Dynamic viscosity',
    factor: 47.88026,
    delta: 0,
    decimalPlaces: 8,
  },
  {
    id: 104,
    name: 'W/(m K)',
    type: 'Thermal conductivity',
    factor: 1,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 105,
    name: 'Btu/(h ft °F)',
    type: 'Thermal conductivity',
    factor: 1.730735,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 106,
    name: 'Btu/(h in °F)',
    type: 'Thermal conductivity',
    factor: 20.76882,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 107,
    name: 'Btu in/(h ft² °F)',
    type: 'Thermal conductivity',
    factor: 0.1442279,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 108,
    name: 'Btu in/(s ft² °F)',
    type: 'Thermal conductivity',
    factor: 519.2204,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 109,
    name: 'cal/(cm s K)',
    type: 'Thermal conductivity',
    factor: 418.68,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 110,
    name: 'cal/(m s °C)',
    type: 'Thermal conductivity',
    factor: 4.1868,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 111,
    name: 'kcal cm/(m² h °C)',
    type: 'Thermal conductivity',
    factor: 0.01163,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 112,
    name: 'kcal/(m h °C)',
    type: 'Thermal conductivity',
    factor: 1.163,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 113,
    name: 'J/kg',
    type: 'Latent Heat',
    factor: 1,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 114,
    name: 'm²/s²',
    type: 'Latent Heat',
    factor: 1,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 115,
    name: 'kcal/kg',
    type: 'Latent Heat',
    factor: 4186.8,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 116,
    name: 'Btu/lb',
    type: 'Latent Heat',
    factor: 2326,
    delta: 0,
    decimalPlaces: 5,
  },
  {
    id: 117,
    name: 'cal/g',
    type: 'Latent Heat',
    factor: 4186.8,
    delta: 0,
    decimalPlaces: 5,
  },
  {
    id: 118,
    name: 'kgf m/kg',
    type: 'Latent Heat',
    factor: 9.80665,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 119,
    name: 'm²',
    type: 'Surface',
    factor: 1,
    delta: 0,
    decimalPlaces: 2,
  },
  { id: 120, name: 'l', type: 'Volume', factor: 1, delta: 0, decimalPlaces: 1 },
  {
    id: 121,
    name: 'W/(m² K)',
    type: 'Heat transfer coefficient',
    factor: 1,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 122,
    name: 'kcal/(m² h °C)',
    type: 'Heat transfer coefficient',
    factor: 1.163,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 123,
    name: 'Btu/(h ft² °F)',
    type: 'Heat transfer coefficient',
    factor: 5.678263,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 124,
    name: 'Btu/(s ft² °F)',
    type: 'Heat transfer coefficient',
    factor: 20441.75,
    delta: 0,
    decimalPlaces: 6,
  },
  {
    id: 125,
    name: 'cal/(cm² s K)',
    type: 'Heat transfer coefficient',
    factor: 41868,
    delta: 0,
    decimalPlaces: 6,
  },
  {
    id: 126,
    name: 'mm(2)',
    type: 'Measure',
    factor: 1,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 127,
    name: 'mm(1)',
    type: 'Measure',
    factor: 1,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 128,
    name: 'kJ/kg',
    type: 'Latent Heat',
    factor: 1000,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 129,
    name: 'barg',
    type: 'Pressure',
    factor: 1,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 130,
    name: 'kcal/kg',
    type: 'Hentalpy',
    factor: 1,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 131,
    name: '€ (EUR)',
    type: 'Currency',
    factor: 1,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 132,
    name: '$ (USD)',
    type: 'Currency',
    factor: 0.8272,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 133,
    name: '£ (GBP)',
    type: 'Currency',
    factor: 1.519895,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 134,
    name: '¥ (JPY)',
    type: 'Currency',
    factor: 0.007811157,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 135,
    name: 'm³',
    type: 'Volume',
    factor: 1000,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 136,
    name: 'cm³',
    type: 'Volume',
    factor: 0.001,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 137,
    name: 'dm³',
    type: 'Volume',
    factor: 1,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 138,
    name: 'kg',
    type: 'Weight',
    factor: 1,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 139,
    name: 'g',
    type: 'Weight',
    factor: 0.001,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 140,
    name: 'kJ/(kg K)',
    type: 'Specific Heat',
    factor: 1000,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 141,
    name: 'l/h',
    type: 'Rate',
    factor: 0.001,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 142,
    name: 'ft²',
    type: 'Surface',
    factor: 0.092903043597,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 143,
    name: 'mPa s',
    type: 'Dynamic viscosity',
    factor: 0.001,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 144,
    name: 'kg/(m² s)',
    type: 'Specific flow',
    factor: 1,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 145,
    name: 'ftH2O',
    type: 'Pressure',
    factor: 0.0298896,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 146,
    name: 'ft³',
    type: 'Volume',
    factor: 28.31685,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 147,
    name: 'g/kg',
    type: 'Specific humidity',
    factor: 0.001,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 148,
    name: 'kg/kg',
    type: 'Specific humidity',
    factor: 1,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 149,
    name: 'lb/lb',
    type: 'Specific humidity',
    factor: 1,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 150,
    name: 'gr/lb',
    type: 'Specific humidity',
    factor: 0.000453592,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 151,
    name: 'm³/s',
    type: 'Rate Water',
    factor: 3600,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 152,
    name: 'm³/h',
    type: 'Rate Water',
    factor: 1,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 153,
    name: 'l/s',
    type: 'Rate Water',
    factor: 3.6,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 154,
    name: 'cft/s',
    type: 'Rate Water',
    factor: 101.94,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 155,
    name: 'cft/min',
    type: 'Rate Water',
    factor: 1.699,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 156,
    name: 'Gal/min',
    type: 'Rate Water',
    factor: 0.2271,
    delta: 0,
    decimalPlaces: 2,
  },
  {
    id: 157,
    name: 'kg/s',
    type: 'Rate Water',
    factor: 3600,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 158,
    name: 'kg/h',
    type: 'Rate Water',
    factor: 1,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 159,
    name: 'lb/s',
    type: 'Rate Water',
    factor: 1632.932532,
    delta: 0,
    decimalPlaces: 4,
  },
  {
    id: 160,
    name: 'lb/h',
    type: 'Rate Water',
    factor: 0.45359244,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 161,
    name: 'kg/24h',
    type: 'Rate Water 24h',
    factor: 1,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 162,
    name: 'lb/24h',
    type: 'Rate Water 24h',
    factor: 0.45359244,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 163,
    name: 'MW',
    type: 'Capacity',
    factor: 1000000,
    delta: 0,
    decimalPlaces: 3,
  },
  {
    id: 164,
    name: 'l/min',
    type: 'Rate',
    factor: 0.06,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 165,
    name: 'A',
    type: 'Current',
    factor: 1,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 166,
    name: 'lb',
    type: 'Weight',
    factor: 0.45359237,
    delta: 0,
    decimalPlaces: 1,
  },
  {
    id: 167,
    name: 'dB(A)',
    type: 'Sound',
    factor: 1,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 168,
    name: 'rpm',
    type: 'Rotation speed',
    factor: 1,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 169,
    name: 'V',
    type: 'Voltage',
    factor: 1,
    delta: 0,
    decimalPlaces: 0,
  },
  {
    id: 170,
    name: 'Hz',
    type: 'Frequency',
    factor: 1,
    delta: 0,
    decimalPlaces: 0,
  },
] as const

export const UNITS_BY_ID: Readonly<Record<number, UnitDef>> =
  Object.fromEntries(UNITS.map((unit) => [unit.id, unit]))

export function getUnitsByType(type: UnitType): UnitDef[] {
  return UNITS.filter((unit) => unit.type === type)
}

export function getUnitsByIds(ids: Iterable<number>): UnitDef[] {
  const idSet = ids instanceof Set ? ids : new Set(ids)
  return UNITS.filter((unit) => idSet.has(unit.id))
}

export function getUnitById(id: number): UnitDef | undefined {
  return UNITS_BY_ID[id]
}

export function getUnitIdByName(
  name: string,
  type?: UnitType,
): number | undefined {
  const found = UNITS.find(
    (unit) => unit.name === name && (type === undefined || unit.type === type),
  )
  return found?.id
}

export function requireUnitIdByName(name: string, type?: UnitType): number {
  const id = getUnitIdByName(name, type)
  if (id === undefined) {
    throw new Error(
      `Unknown unit name "${name}"${type ? ` for type "${type}"` : ''}`,
    )
  }
  return id
}
